export const posts = [
    {
        id: '1',
        imagePath: '/01.webp',
        authorName: 'Mark Dinn',
        authorId: '1',
        created: '04 Apr 2022',
        img: '/mark-dinn.webp',
        genre: 'Art',

        heading: 'How to make toys from old Olarpaper',
        brief: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blan...',
        detail: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blandit euismod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo vel ad consectetur ut aperiam. Itaque eligendi natus aperiam? Excepturi repellendus consequatur quibusdam optio expedita praesentium est adipisci dolorem ut eius!',
        isFeatured: true,
        tag: 'diy',
    },
    {
        id: '2',
        imagePath: '/03.webp',
        authorName: 'Mark Dinn',
        authorId: '1',
        created: '04 Apr 2022',
        img: '/mark-dinn.webp',
        genre: 'Art',

        heading: 'How to make toys from old Olarpaper',
        brief: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blan...',
        detail: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blandit euismod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo vel ad consectetur ut aperiam. Itaque eligendi natus aperiam? Excepturi repellendus consequatur quibusdam optio expedita praesentium est adipisci dolorem ut eius!',
        isFeatured: false,
        tag: 'toy',
    },
    {
        id: '3',
        imagePath: '/02.webp',
        authorName: 'John Doe',
        authorId: '2',
        created: '04 Apr 2022',
        img: '/john-doe.webp',
        genre: 'Web development',

        heading: 'How to make toys from old Olarpaper',
        brief: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blan...',
        detail: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blandit euismod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo vel ad consectetur ut aperiam. Itaque eligendi natus aperiam? Excepturi repellendus consequatur quibusdam optio expedita praesentium est adipisci dolorem ut eius!',
        isFeatured: false,
        tag: 'diy',
    },
    {
        id: '4',
        imagePath: '/04.webp',
        authorName: 'John Doe',
        authorId: '2',
        created: '04 Apr 2022',
        img: '/john-doe.webp',
        genre: 'Accessories',

        heading: 'Why a balloon is a flexible bag',
        brief: 'A balloon is a flexible bag that can be inflated with a gas, such as helium, hydrogen, nitrous oxide, oxygen, and air. For special tasks, balloons can be filled with smoke, liquid water, granular med...',
        detail: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blandit euismod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo vel ad consectetur ut aperiam. Itaque eligendi natus aperiam? Excepturi repellendus consequatur quibusdam optio expedita praesentium est adipisci dolorem ut eius!',
        isFeatured: true,
        tag: 'toy',
    },
    {
        id: '5',
        imagePath: '/05.webp',
        authorName: 'John Doe',
        authorId: '2',
        created: '04 Apr 2022',
        img: '/john-doe.webp',
        genre: 'Accessories',

        heading: 'Why a balloon is a flexible bag that can be inflated with a gas',
        brief: 'A balloon is a flexible bag that can be inflated with a gas, such as helium, hydrogen, nitrous oxide, oxygen, and air. For special tasks, balloons can be filled with smoke, liquid water, granular med...',
        detail: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blandit euismod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo vel ad consectetur ut aperiam. Itaque eligendi natus aperiam? Excepturi repellendus consequatur quibusdam optio expedita praesentium est adipisci dolorem ut eius!',
        isFeatured: false,
        tag: 'diy',
    },
    {
        id: '6',
        imagePath: '/06.webp',
        authorName: 'John Doe',
        authorId: '2',
        created: '04 Apr 2022',
        img: '/john-doe.webp',
        genre: 'Accessories',

        heading: 'Why a balloon is a flexible bag that can be inflated with a gas',
        brief: 'A balloon is a flexible bag that can be inflated with a gas, such as helium, hydrogen, nitrous oxide, oxygen, and air. For special tasks, balloons can be filled with smoke, liquid water, granular med...',
        detail: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blandit euismod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo vel ad consectetur ut aperiam. Itaque eligendi natus aperiam? Excepturi repellendus consequatur quibusdam optio expedita praesentium est adipisci dolorem ut eius!',
        isFeatured: false,
        tag: 'toy',
    },
    {
        id: '7',
        imagePath: '/07.webp',
        authorName: 'Mark Dinn',
        authorId: '1',
        created: '04 Apr 2022',
        img: '/john-doe.webp',
        genre: 'Accessories',

        heading: 'Why a balloon is a flexible bag that can be inflated with a gas',
        brief: 'A balloon is a flexible bag that can be inflated with a gas, such as helium, hydrogen, nitrous oxide, oxygen, and air. For special tasks, balloons can be filled with smoke, liquid water, granular med...',
        detail: 'Nemo vel ad consectetur namut rutrum ex, venenatis sollicitudin urna. Aliquam erat volutpat. Integer eu ipsum sem. Ut bibendum lacus vestibulum maximus suscipit. Quisque vitae nibh iaculis neque blandit euismod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo vel ad consectetur ut aperiam. Itaque eligendi natus aperiam? Excepturi repellendus consequatur quibusdam optio expedita praesentium est adipisci dolorem ut eius!',
        isFeatured: true,
        tag: 'diy',
    },
];

export const authors = [
    {
        authorName: 'John Doe',
        id: '2',
        info: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostr navigation et dolore magna aliqua.',
        img: 'https://bookworm-light-nextjs.vercel.app/_next/image?url=%2Fimages%2Fauthors%2Fjohn-doe.jpg&w=256&q=75',
    },
    {
        authorName: 'Mark Dinn',
        id: '1',
        info: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostr navigation et dolore magna aliqua.',
        img: 'https://bookworm-light-nextjs.vercel.app/_next/image?url=%2Fimages%2Fauthors%2Fmark-dinn.jpg&w=256&q=75',
    },
];
